spring:
    profiles:
        active: test

---
server:
    port: 3355
spring:
    profiles: test
    application:
        name: springcloud-config-test-client
---
server:
    port: 3356
spring:
    profiles: dev
    application:
        name: springcloud-config-dev-client